/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
pub struct clothes {
    pub hat: bool,
    pub scarf: bool,
}
#[repr(C)]
pub struct yak_shaver {
    pub id: ::core::ffi::c_uint,
    pub name: [::core::ffi::c_char; 64usize],
    pub owner: *const ::core::ffi::c_char,
    pub description: *mut ::core::ffi::c_char,
    pub children: *mut *mut ::core::ffi::c_char,
    pub clothes: *mut clothes,
    pub list: yak_shaver__bindgen_ty_1,
}
#[repr(C)]
pub struct yak_shaver__bindgen_ty_1 {
    pub next: *mut yak_shaver,
    pub prev: *mut yak_shaver,
}
