/* automatically generated by rust-bindgen 0.71.1 */

unsafe extern "C" {
    pub fn concat(
        left: *const ::core::ffi::c_char,
        right: *const ::core::ffi::c_char,
    ) -> *mut ::core::ffi::c_char;
}
